# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(help_text='Submeta aqui a primeira foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 1')),
                ('pic2', models.ImageField(help_text='Submeta aqui a segunda foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 2')),
                ('pic3', models.ImageField(help_text='Submeta aqui a terceira foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(help_text="Este conte\xfado ir\xe1 aparecer na p\xe1gina 'Quem somos'. Este campo aceita c\xf3digo HTML. Por exemplo, utilize a tag &lt;br&gt; para quebrar linha (Texto &lt;br&gt; continua\xe7\xe3o do texto).", verbose_name='Descri\xe7\xe3o da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='maps_url',
            field=models.TextField(blank=True, help_text='Informe a URL do map a gerado pela API do Google Maps (apenas o campo src).', verbose_name='URL da localiza\xe7\xe3o da empresa (Google Maps)'),
        ),
    ]
