# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20160813_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='description1',
            field=models.TextField(blank=True, help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='description2',
            field=models.TextField(blank=True, help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='description3',
            field=models.TextField(blank=True, help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='title1',
            field=models.CharField(default='', max_length=50, verbose_name='T\xedtulo da foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startpage',
            name='title2',
            field=models.CharField(default='', max_length=50, verbose_name='T\xedtulo da foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startpage',
            name='title3',
            field=models.CharField(default='', max_length=50, verbose_name='T\xedtulo da foto'),
            preserve_default=False,
        ),
    ]
