# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20160813_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='description1',
            field=models.TextField(blank=True, help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='description2',
            field=models.TextField(blank=True, help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='description3',
            field=models.TextField(blank=True, help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='title1',
            field=models.CharField(default='', max_length=50, verbose_name='T\xedtulo da foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startpage',
            name='title2',
            field=models.CharField(default='', max_length=50, verbose_name='T\xedtulo da foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startpage',
            name='title3',
            field=models.CharField(default='', max_length=50, verbose_name='T\xedtulo da foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startpage',
            name='pic1',
            field=models.ImageField(help_text='Submeta aqui a primeira foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='pic2',
            field=models.ImageField(help_text='Submeta aqui a segunda foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='pic3',
            field=models.ImageField(help_text='Submeta aqui a terceira foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 3'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
