# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20160813_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startpage',
            name='description1',
            field=models.TextField(help_text='Este texto aparecer\xe1 embaixo do t\xedtulo na p\xe1gina inicial.', verbose_name='Descri\xe7\xe3o da foto'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='pic2',
            field=models.ImageField(blank=True, help_text='Submeta aqui a segunda foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='pic3',
            field=models.ImageField(blank=True, help_text='Submeta aqui a terceira foto para a p\xe1gina inicial.', upload_to='uploads/pictures/start_page/%Y/%m/%d/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='title2',
            field=models.CharField(blank=True, max_length=50, verbose_name='T\xedtulo da foto'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='title3',
            field=models.CharField(blank=True, max_length=50, verbose_name='T\xedtulo da foto'),
        ),
    ]
