# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 23:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s+]+$', 'Ops, este n\xe3o \xe9 um nome v\xe1lido. Utilize somente caracteres alfab\xe9ticos.')], verbose_name='Solicitante')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='E-mail do solicitante')),
                ('requester_phone', models.CharField(help_text='Use somente n\xfameros.', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9\\s+]+$', 'Ops, este n\xe3o \xe9 um n\xfamero v\xe1lido. Utilize somente n\xfameros.')], verbose_name='Telefone do solicitante')),
                ('requester_address', models.CharField(help_text='Para quem ofereceremos esse servi\xe7o?!', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9\\s+]+$', 'Ops, este n\xe3o \xe9 um n\xfamero v\xe1lido. Utilize somente n\xfameros.')], verbose_name='Endere\xe7o do solicitante')),
                ('message', models.TextField(verbose_name='Mensagem/Detalhes')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Servi\xe7o'),
        ),
    ]
