# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160723_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Budget')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Service')),
            ],
        ),
    ]
