# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160723_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensagem/Detalhes'),
        ),
    ]
