# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 17:57
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160723_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 29, 17, 57, 24, 840719, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='requester_address',
            field=models.CharField(help_text='Para quem ofereceremos esse servi\xe7o?!', max_length=100, verbose_name='Endere\xe7o do solicitante'),
        ),
        migrations.AlterField(
            model_name='budgetservice',
            name='quantity',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
