# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 16:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160801_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\xe1\xe9\xed\xf3\xfa\xe0\xe2\xea\xf4\xe3\xf5\xfc\xe7\xc1\xc9\xcd\xd3\xda\xc0\xc2\xca\xd4\xc3\xd5\xdc\xc7 ]+$', 'Ops, este n\xe3o \xe9 um nome v\xe1lido. Utilize somente caracteres alfab\xe9ticos.')], verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Use somente n\xfameros.', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9\\s+]+$', 'Ops, este n\xe3o \xe9 um n\xfamero v\xe1lido. Utilize somente n\xfameros.')], verbose_name='Telefone')),
                ('resume', models.FileField(help_text='Submeta aqui o seu curr\xedculo em .PDF, .DOC ou .DOCX.', upload_to='uploads/resume/%Y/%m/%d/', verbose_name='Curr\xedculo')),
            ],
        ),
    ]
