# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_joinusrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusrequest',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joinusrequest',
            name='resume',
            field=models.FileField(help_text="Submeta aqui o seu curr\xedculo em '.PDF' ou '.DOC'.", upload_to='uploads/resumes/%Y/%m/%d/', verbose_name='Curr\xedculo'),
        ),
    ]
