# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 16:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160809_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='requester',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\xe1\xe9\xed\xf3\xfa\xe0\xe2\xea\xf4\xe3\xf5\xfc\xe7\xc1\xc9\xcd\xd3\xda\xc0\xc2\xca\xd4\xc3\xd5\xdc\xc7 ]+$', 'Ops, este n\xe3o \xe9 um nome v\xe1lido. Utilize somente caracteres alfab\xe9ticos.')], verbose_name='Nome do solicitante'),
        ),
    ]
